  on:
    push:
      branches:
        - master
  jobs:
    build-deploy:
      name: Logistic-Commodity-Microservice
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup-JDK 17
          uses: actions/ setup-java@v4
          with:
            distribution: 'zulu'
            java-version: 17

        - name: Unit Test
          run: mvn -B test --file pom.xml

        - name: Build Application
          run: |
            mvn clean
            mvn -B package --file pom.xml